parameters:
    autoplicity.host: http://autoplicity.com
    autoplicity.path.brandPageUrls: %ROOT_PATH%/configs/autoplicity/brand-page-urls.csv

    autoplicity.client.options: 
        request.options: 
            proxy: @=container.hasParameter('proxy') ? parameter('proxy') : ''
    
    autoplicity.imagePathCollector.poolSize: 3
    autoplicity.imagePathCollector.urlsChunkSize: 1000

    autoplicity.imagesCollector.poolSize: 3
    
    autoplicity.executor.poolSize: 5
    autoplicity.executor.iterationTimOut: 1

    autoplicity.logger.error.name: autoplicity-error.log
    autoplicity.logger.debug.name: autoplicity-debug.log

services:
    autoplicity.client:
        class: Guzzle\Http\Client
        arguments: ['', %autoplicity.client.options%]
        calls:
            - [setBaseUrl, [%autoplicity.host%]]

    autoplicity.logger.error.handler:
        class: Monolog\Handler\StreamHandler
        arguments: [%app.var.dir%/autoplicity/log/%autoplicity.logger.error.name%, @=constant('\\\Monolog\\\Logger::WARNING'), false]
        public: false

    autoplicity.logger.debug.handler:
        class: Monolog\Handler\StreamHandler
        arguments: [%app.var.dir%/autoplicity/log/%autoplicity.logger.debug.name%, @=constant('\\\Monolog\\\Logger::DEBUG'), false]
        public: false

    autoplicity.logger:
        class: Monolog\Logger
        arguments: [autoplicity]
        calls:
            - [pushHandler, [@autoplicity.logger.debug.handler]]
            - [pushHandler, [@autoplicity.logger.error.handler]]