imports:
    - { resource: 'proxies.yml', ignore_errors: true }
    - { resource: 'autoplicity/autoplicity.yml'}
    - { resource: 'amazon/amazon.yml'}

parameters:
    app.name: Images Parser
    app.version: 0.1
    
    app.memory_limit: 256M
        
    app.urls.dir.name: produc-urls
    app.imgInfo.dir.name: produc-images-info
       
    app.imageInfoHeaders:
        - sku
        - src
        - order
        - representative-photo
        - product-url

    logger.error.handler.name: application-error.log
    logger.debug.handler.name: application-debug.log

services:
    app:
        class: Symfony\Component\Console\Application
        arguments: [%app.name%, %app.version%]

    crawler:
        class: Symfony\Component\DomCrawler\Crawler
        scope: prototype